import nodemailer from 'nodemailer'

export async function sendReportEmail(summary) {
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_FROM,
      pass: process.env.EMAIL_PASSWORD, // Use a Gmail App Password
    },
  })

  const sourceRows = summary.topSources
    .map(s => `<tr><td style="padding:6px 12px;color:#888;">${s.source}</td><td style="padding:6px 12px;text-align:right;">${s.count} visits</td></tr>`)
    .join('')

  const html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { background: #0d0d0d; color: #f5f5f5; font-family: sans-serif; margin: 0; padding: 0; }
    .wrap { max-width: 560px; margin: 0 auto; padding: 40px 24px; }
    .logo { font-size: 22px; font-weight: 800; letter-spacing: -0.5px; margin-bottom: 32px; }
    .arc { color: #4fc3f7; }
    h2 { font-size: 20px; font-weight: 700; margin-bottom: 24px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 32px; }
    .card { background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 8px; padding: 16px; }
    .label { font-size: 11px; color: #888; letter-spacing: 0.5px; text-transform: uppercase; margin-bottom: 6px; }
    .value { font-size: 24px; font-weight: 700; color: #4fc3f7; }
    table { width: 100%; border-collapse: collapse; }
    .footer { font-size: 12px; color: #555; margin-top: 32px; padding-top: 24px; border-top: 1px solid #2a2a2a; }
  </style>
</head>
<body>
<div class="wrap">
  <div class="logo">ARC<span class="arc">LIT</span></div>
  <h2>Weekly Analytics Report</h2>
  <p style="color:#888;font-size:14px;margin-bottom:28px;">${summary.period}</p>

  <div class="grid">
    <div class="card"><div class="label">Page views</div><div class="value">${summary.pageViews}</div></div>
    <div class="card"><div class="label">Orders</div><div class="value">${summary.totalOrders}</div></div>
    <div class="card"><div class="label">Revenue</div><div class="value">$${summary.totalRevenue}</div></div>
    <div class="card"><div class="label">Avg order value</div><div class="value">$${summary.aov}</div></div>
    <div class="card"><div class="label">Conversion rate</div><div class="value">${summary.conversionRate}%</div></div>
    <div class="card"><div class="label">Cart abandonment</div><div class="value">${summary.cartAbandonmentRate}%</div></div>
  </div>

  <h2 style="font-size:16px;margin-bottom:16px;">Traffic sources</h2>
  <table>
    <thead>
      <tr style="border-bottom:1px solid #2a2a2a;">
        <th style="padding:6px 12px;text-align:left;font-size:12px;color:#888;font-weight:500;">Source</th>
        <th style="padding:6px 12px;text-align:right;font-size:12px;color:#888;font-weight:500;">Visits</th>
      </tr>
    </thead>
    <tbody>${sourceRows}</tbody>
  </table>

  <div class="footer">
    This report was auto-generated by ArcLit analytics.<br>
    To trigger a manual report: GET /api/send-report?secret=YOUR_ADMIN_PASSWORD
  </div>
</div>
</body>
</html>
  `

  await transporter.sendMail({
    from: `ArcLit Analytics <${process.env.EMAIL_FROM}>`,
    to: process.env.EMAIL_TO,
    subject: `ArcLit Weekly Report — ${new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'short', year: 'numeric' })}`,
    html,
  })
}
